# Generated by Django 5.1.1 on 2024-11-27 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='image',
        ),
        migrations.AddField(
            model_name='request',
            name='room_image',
            field=models.ImageField(blank=True, null=True, upload_to='requests/'),
        ),
    ]
